name: Run Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v -race ./...
